#wap to display your roll number ,name and section in different lines
print("Enter your name:")
x = input()
print("NAME:"+x)
print("Enter your roll number:")
y = input()
print("ROLL:"+y)
print("Enter your section:")
z = input()
print("SECTION:"+z)
